package rst

import "strings"

// This file ports docutils.utils.punctuation_chars' character classes and
// docutils.parsers.rst.states.Inliner's start_string_prefix/end_string_suffix
// boundary rules verbatim -- not "any punctuation" (this parser's own
// earlier, simpler approximation via unicode.IsPunct, which treated an
// opening and a closing bracket/quote identically). Real docutils
// distinguishes them: a markup start-string may be preceded by an OPENER or
// a DELIMITER but never a CLOSER or a CLOSING-DELIMITER, and a markup
// end-string may be followed by a CLOSER, a DELIMITER, or a
// CLOSING-DELIMITER but never an OPENER -- which is exactly why real
// docutils accepts "(*emphasis*)" and "*emphasis*." but rejects
// ")*emphasis*(" and "*emphasis*)" as genuine markup at all (see the
// go-docutils test suite corpus's own test_inline_markup.py fixtures, read
// directly, not inferred).
//
// openers/closers are docutils.utils.punctuation_chars.{openers,closers}
// VERBATIM, in their original left-to-right order (confirmed range-syntax
// free -- no literal "-" in either), because quotedStart's positional
// pairing (openers[i] <-> closers[i]) depends on that exact order; an
// EARLIER version of this file ran them through the same regex-range
// expansion delimiters needs, which reorders by code point and silently
// broke every same-index pairing that wasn't already in code-point order
// (caught by cross-checking quotedStart against Python's own match_chars
// for a battery of real quote pairs, not by inspection -- the character
// SETS matched the reference perfectly even with the wrong order, since
// membership doesn't care about position). delimiters/closing_delimiters
// ARE regex-range syntax in the source (e.g. "a-z"), so those two ARE the
// fully expanded membership sets, generated by compiling each as a Python
// regex character class and testing every Unicode code point against it.
// Every character below is written as a \uXXXX/\UXXXXXXXX escape naming
// its exact code point, deliberately, not typed or copied as a glyph: a
// first attempt at this file used literal glyphs and silently substituted
// at least two visually-similar-but-distinct characters (a plain semicolon
// for the Greek question mark U+037E, and the CJK angle brackets
// U+3008/U+3009 for the mathematical ones U+2329/U+232A) -- caught only by
// cross-checking every code point against the Python reference, not by
// review.
const punctOpeners = "\"'(<\\[{\u0f3a\u0f3c\u169b\u2045\u207d\u208d\u2329\u2768\u276a\u276c\u276e\u2770\u2772\u2774\u27c5\u27e6\u27e8\u27ea\u27ec\u27ee\u2983\u2985\u2987\u2989\u298b\u298d\u298f\u2991\u2993\u2995\u2997\u29d8\u29da\u29fc\u2e22\u2e24\u2e26\u2e28\u3008\u300a\u300c\u300e\u3010\u3014\u3016\u3018\u301a\u301d\u301d\ufd3e\ufe17\ufe35\ufe37\ufe39\ufe3b\ufe3d\ufe3f\ufe41\ufe43\ufe47\ufe59\ufe5b\ufe5d\uff08\uff3b\uff5b\uff5f\uff62\u00ab\u2018\u201c\u2039\u2e02\u2e04\u2e09\u2e0c\u2e1c\u2e20\u201a\u201e\u00bb\u2019\u201d\u203a\u2e03\u2e05\u2e0a\u2e0d\u2e1d\u2e21\u201b\u201f"
const punctClosers = "\"')>\\]}\u0f3b\u0f3d\u169c\u2046\u207e\u208e\u232a\u2769\u276b\u276d\u276f\u2771\u2773\u2775\u27c6\u27e7\u27e9\u27eb\u27ed\u27ef\u2984\u2986\u2988\u298a\u298c\u298e\u2990\u2992\u2994\u2996\u2998\u29d9\u29db\u29fd\u2e23\u2e25\u2e27\u2e29\u3009\u300b\u300d\u300f\u3011\u3015\u3017\u3019\u301b\u301e\u301f\ufd3f\ufe18\ufe36\ufe38\ufe3a\ufe3c\ufe3e\ufe40\ufe42\ufe44\ufe48\ufe5a\ufe5c\ufe5e\uff09\uff3d\uff5d\uff60\uff63\u00bb\u2019\u201d\u203a\u2e03\u2e05\u2e0a\u2e0d\u2e1d\u2e21\u201b\u201f\u00ab\u2018\u201c\u2039\u2e02\u2e04\u2e09\u2e0c\u2e1c\u2e20\u201a\u201e"
const punctDelimiters = "-/:\u00a1\u00b7\u00bf\u037e\u0387\u055a\u055b\u055c\u055d\u055e\u055f\u0589\u058a\u05be\u05c0\u05c3\u05c6\u05f3\u05f4\u0609\u060a\u060c\u060d\u061b\u061e\u061f\u066a\u066b\u066c\u066d\u06d4\u0700\u0701\u0702\u0703\u0704\u0705\u0706\u0707\u0708\u0709\u070a\u070b\u070c\u070d\u07f7\u07f8\u07f9\u0830\u0831\u0832\u0833\u0834\u0835\u0836\u0837\u0838\u0839\u083a\u083b\u083c\u083d\u083e\u0964\u0965\u0970\u0df4\u0e4f\u0e5a\u0e5b\u0f04\u0f05\u0f06\u0f07\u0f08\u0f09\u0f0a\u0f0b\u0f0c\u0f0d\u0f0e\u0f0f\u0f10\u0f11\u0f12\u0f85\u0fd0\u0fd1\u0fd2\u0fd3\u0fd4\u104a\u104b\u104c\u104d\u104e\u104f\u10fb\u1361\u1362\u1363\u1364\u1365\u1366\u1367\u1368\u1400\u166d\u166e\u16eb\u16ec\u16ed\u1735\u1736\u17d4\u17d5\u17d6\u17d8\u17d9\u17da\u1800\u1801\u1802\u1803\u1804\u1805\u1806\u1807\u1808\u1809\u180a\u1944\u1945\u19de\u19df\u1a1e\u1a1f\u1aa0\u1aa1\u1aa2\u1aa3\u1aa4\u1aa5\u1aa6\u1aa8\u1aa9\u1aaa\u1aab\u1aac\u1aad\u1b5a\u1b5b\u1b5c\u1b5d\u1b5e\u1b5f\u1b60\u1c3b\u1c3c\u1c3d\u1c3e\u1c3f\u1c7e\u1c7f\u1cd3\u2010\u2011\u2012\u2013\u2014\u2015\u2016\u2017\u2020\u2021\u2022\u2023\u2024\u2025\u2026\u2027\u2030\u2031\u2032\u2033\u2034\u2035\u2036\u2037\u2038\u203b\u203c\u203d\u203e\u2041\u2042\u2043\u2047\u2048\u2049\u204a\u204b\u204c\u204d\u204e\u204f\u2050\u2051\u2053\u2055\u2056\u2057\u2058\u2059\u205a\u205b\u205c\u205d\u205e\u2cf9\u2cfa\u2cfb\u2cfc\u2cfe\u2cff\u2e00\u2e01\u2e06\u2e07\u2e08\u2e0b\u2e0e\u2e0f\u2e10\u2e11\u2e12\u2e13\u2e14\u2e15\u2e16\u2e17\u2e18\u2e19\u2e1a\u2e1b\u2e1e\u2e1f\u2e2a\u2e2b\u2e2c\u2e2d\u2e2e\u2e30\u2e31\u3001\u3002\u3003\u301c\u3030\u303d\u30a0\u30fb\ua4fe\ua4ff\ua60d\ua60e\ua60f\ua673\ua67e\ua6f2\ua6f3\ua6f4\ua6f5\ua6f6\ua6f7\ua874\ua875\ua876\ua877\ua8ce\ua8cf\ua8f8\ua8f9\ua8fa\ua92e\ua92f\ua95f\ua9c1\ua9c2\ua9c3\ua9c4\ua9c5\ua9c6\ua9c7\ua9c8\ua9c9\ua9ca\ua9cb\ua9cc\ua9cd\ua9de\ua9df\uaa5c\uaa5d\uaa5e\uaa5f\uaade\uaadf\uabeb\ufe10\ufe11\ufe12\ufe13\ufe14\ufe15\ufe16\ufe19\ufe30\ufe31\ufe32\ufe45\ufe46\ufe49\ufe4a\ufe4b\ufe4c\ufe50\ufe51\ufe52\ufe54\ufe55\ufe56\ufe57\ufe58\ufe5f\ufe60\ufe61\ufe63\ufe68\ufe6a\ufe6b\uff01\uff02\uff03\uff05\uff06\uff07\uff0a\uff0c\uff0d\uff0e\uff0f\uff1a\uff1b\uff1f\uff20\uff3c\uff61\uff64\uff65\U00010100\U00010101\U0001039f\U000103d0\U00010857\U0001091f\U0001093f\U00010a50\U00010a51\U00010a52\U00010a53\U00010a54\U00010a55\U00010a56\U00010a57\U00010a58\U00010a7f\U00010b39\U00010b3a\U00010b3b\U00010b3c\U00010b3d\U00010b3e\U00010b3f\U000110bb\U000110bc\U000110be\U000110bf\U000110c0\U000110c1\U00012470\U00012471\U00012472\U00012473"
const punctClosingDelimiters = "!,.;?\\"

// punctQuotePairs mirrors docutils.utils.punctuation_chars.quote_pairs: an
// opener that additionally matches one or more closers BESIDES its own
// same-index closer (mixed quotation-mark conventions across languages --
// French, German, Polish, Hungarian, Greek, ... -- where the SAME character
// opens a quotation in one convention and closes it in another).
var punctQuotePairs = map[rune]string{
	'\u00bb': "\u00bb",
	'\u2018': "\u201a",
	'\u2019': "\u2019",
	'\u201a': "\u2018\u2019",
	'\u201c': "\u201e",
	'\u201e': "\u201c\u201d",
	'\u201d': "\u201d",
	'\u203a': "\u203a",
}

func isOpener(r rune) bool           { return strings.ContainsRune(punctOpeners, r) }
func isCloser(r rune) bool           { return strings.ContainsRune(punctClosers, r) }
func isDelimiterChar(r rune) bool    { return strings.ContainsRune(punctDelimiters, r) }
func isClosingDelimiter(r rune) bool { return strings.ContainsRune(punctClosingDelimiters, r) }

// quotedStart mirrors punctuation_chars.match_chars(prestart, poststart),
// called from real docutils' Inliner.quoted_start: true when prestart is a
// registered opener whose matching closer (same position in the ordered
// openers/closers strings) IS poststart, or poststart is one of prestart's
// extra quote_pairs partners. A markup start-string immediately sandwiched
// between such a pair (e.g. "(*)text", opener "(" then closer ")" with
// nothing else between) is rejected as a genuine start even though the
// basic boundary rule alone would accept it.
//
// Deliberately uses the FIRST occurrence of prestart in openers (Python's
// str.index, which match_chars calls, does the same), not every occurrence
// — real docutils' own openers string repeats exactly one character (U+301D
// "〝", at two positions pairing with two different closers, U+301E and
// U+301F); only the first pairing is ever reachable through match_chars,
// the second is a real, if obscure, quirk of the reference implementation
// this mirrors rather than improves on.
func quotedStart(prestart, poststart rune) bool {
	byteIdx := strings.IndexRune(punctOpeners, prestart)
	if byteIdx < 0 {
		// Python's own match_chars returns False here directly (a bare
		// `except ValueError: return False`) without even consulting
		// quote_pairs — every quote_pairs key does also appear in openers,
		// so this branch is unreachable for any real quote_pairs lookup,
		// but matching the exact control flow rather than an
		// only-coincidentally-equivalent shortcut is the safer choice.
		return false
	}
	runeIdx := len([]rune(punctOpeners[:byteIdx]))
	closersRunes := []rune(punctClosers)
	if runeIdx < len(closersRunes) && poststart == closersRunes[runeIdx] {
		return true
	}
	if extra, ok := punctQuotePairs[prestart]; ok && strings.ContainsRune(extra, poststart) {
		return true
	}
	return false
}
